name: Update
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly
permissions:
  contents: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tinted Builder Rust
        uses: tinted-theming/tinted-builder-rust@v0.13.1

      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add presets
          git commit -m "chore: Presets updated" || true
          git push
