name: Update
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly
permissions:
  contents: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Tinted Builder Rust
        uses: tinted-theming/tinted-builder-rust@86be23310a1f88de3da5d09449c7218d1b7c3d7f # v0.20.1

      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add presets
          git commit -m "chore: Presets updated" || true
          git push
